version: '3'
services:
 web:
   image: twohill/silverstripe4
   working_dir: /var/www
   ports:
    - 80:80
   volumes:
    - .:/var/www/html

 database:
   image: mariadb
   volumes:
    - db-data:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: "${SS_DATABASE_PASSWORD}"  #set this via your env variable

volumes:
 db-data:
