version: '3'
services:
  database:
    container_name: webserver-db
    image: mariadb
    networks:
      devserver:
        ipv4_address: 172.158.0.98
    volumes:
      - ./databases:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"  #set this via your env variable
    ports:
      - 3306:3306

  adminer:
    container_name: webserver-adminer
    image: adminer:standalone
    networks:
      devserver:
        ipv4_address: 172.158.0.100
    ports:
      - 8888:8080
    depends_on:
      - database

  web:
    container_name: webserver-web
    image: ilateral/php:7.4-apache-buster
    working_dir: /var/www
    restart: always
    networks:
      devserver:
        ipv4_address: 172.158.0.99
    build:
      context: ./build/web
      args:
        USER_ID: ${WWW_USER_ID:-0}
        GROUP_ID: ${WWW_GROUP_ID:-0}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./sites:/var/www/html
      - ./files:/home/www-data/files
      - ~/.ssh:/home/www-data/.ssh
    depends_on:
      - database
    links:
      - database

networks:
  devserver:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.158.0.0/16