version: '3'
services:
  database:
    container_name: dev-server-db
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"  #set this via your env variable
    ports:
      - 3306:3306

  web:
    container_name: dev-server-web
    image: ilateral/php:7.3-apache-stretch
    working_dir: /var/www
    restart: always
    build:
      context: ./build/web
      args:
        USER_ID: ${WWW_USER_ID:-0}
        GROUP_ID: ${WWW_GROUP_ID:-0}
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html
    depends_on:
      - database
    links:
      - database

volumes:
 db-data: